version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - npm run build
      - echo "Invalidating CloudFront distribution $DISTRIBUTION_ID..."
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
