version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
      - echo "Invalidating CloudFront distribution ${env:DISTRIBUTION_ID}..."
      - aws cloudfront create-invalidation \
          --distribution-id ${env:DISTRIBUTION_ID} \
          --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
