version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
      - echo "Invalidating CloudFront distribution E2XD8TYQPLEIPI..."
      - aws cloudfront create-invalidation \
          --distribution-id E2XD8TYQPLEIPI \
          --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
