version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    working-directory: backend
    commands:
      - npm install -g serverless
      - npm install
  build:
    working-directory: backend
    commands:
      - serverless deploy
