version: 0.2

phases:
  install:
    commands:
      - cd backend
      - npm install -g serverless  
      - npm install 
  build:
    commands:
      - npm run build
      - serverless deploy  

artifacts:
  base-directory: backend/dist  
  files:
    - '**/*'
  name: BackendBuildOutput
