version: 0.2

phases:
  install:
    working-directory: backend  
    commands:
      - npm install -g serverless  
      - npm install 
  build:
    working-directory: backend 
    commands:
      - serverless deploy 

artifacts:
  files:
    - '**/*'
  base-directory: backend 
