service: Elibrary-serverless-app

provider:
  name: aws
  timeout: 300
  runtime: nodejs18.x
  region: ${env:REGION}
  environment:
    PORT: ${env:PORT}
    MONGO_URI: ${env:MONGO_URI}
    SECRET_KEY: ${env:SECRET_KEY}
    GOOGLE_API_KEY: ${env:GOOGLE_API_KEY}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    ACCESS_KEY_ID:  ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY:  ${env:SECRET_ACCESS_KEY}

functions:
  api:
    handler: dist/handler.handler 
    events:
      - http: ANY /
      - http: ANY {proxy+}


plugins:
  - serverless-offline
